### ISSUE TITLE
按照api写的js脚本，但是总是报错

### ISSUE THREAD

**Issue by iicanf** [mrwutong/cordova-qdc-baidu-location#6]
![screenshot from 2015-12-13 19 14 12](https://cloud.githubusercontent.com/assets/2391122/11766689/d5c8e82c-a1cd-11e5-887c-f6595e70dff5.png)

**Comment by nolure** [comment]
@iicanf  请问你这个调试 是怎么弄得啊 打包之后可以在chrome里直接调试？
